INSERT INTO builds (beginner, end_game) VALUES
('food', 'stealth'),
('vanguard', 'tank'),
('bloodied', 'melee'),
('berserker', 'heavy gunner'),
('junkie', 'melee'),
('farmer', 'vanguard'),
('pvp', 'stealth'),
('commando', 'junkie'),
('bloodied', 'junkie'),
('junkie', 'melee'),
('commando', 'stealth'),
('tank', 'commando');

INSERT INTO characters (sex, lvl, faction, price, build_id) VALUES
( 'female', 15, 'Brotherhood of Steel', 10, 1),
( 'male', 45, 'Enclave', 50, 2),
( 'female', 100, 'Raiders', 75, 3),
( 'female', 200, 'Responders', 89, 4),
( 'male', 77, 'Blood Eagles', 125, 5),
( 'male', 365, 'Responders', 55, 6),
( 'female', 53, 'Slavers', 110,  7),
( 'female', 20, 'Fanatics', 35, 8),
( 'female', 72, 'Brotherhood of Steel', 65, 9),
( 'male', 25, 'Raiders', 55, 10),
( 'female', 525 , 'Blood Eagles', 125, 11),
( 'female', 35, 'Brotherhood of Steel', 250, 12);

INSERT INTO inventory (src, character_id) VALUES
('https://imgur.com/aKuYJIO.png', 1),
('https://imgur.com/Uz7Gw4X.png', 1),
('https://imgur.com/dy5UolK.png', 1),
('https://imgur.com/bmEKbmI.png', 2),
('https://imgur.com/AVT7PCg.png', 2),
('https://imgur.com/PYvhJtw.png', 2),
('https://imgur.com/aLEposw.png', 3),
('https://imgur.com/LiaBliM.png', 3),
('https://imgur.com/IyhB7Fu.png', 3),
('https://imgur.com/uMo8ORz.png', 4),
('https://imgur.com/nwk2Wmr.png', 4),
('https://imgur.com/L7kYZwH.png', 4),
('https://imgur.com/gZwcPzq.png', 5),
('https://imgur.com/8xOuIux.png', 5),
('https://imgur.com/LL8Fhdh.png', 5),
('https://imgur.com/kIMIHYm.png', 6),
('https://imgur.com/SsLQ95x.png', 6),
('https://imgur.com/uABmS7P.png', 6),
('https://imgur.com/x9epSBq.png', 7),
('https://imgur.com/Ey2RL5Q.png', 7),
('https://imgur.com/CnsA0j3.png', 7),
('https://imgur.com/CND7Izt.png', 8),
('https://imgur.com/TlIsflG.png', 8),
('https://imgur.com/7kE4Qtl.png', 8),
('https://imgur.com/LjL2KAs.png', 9),
('https://imgur.com/c4Rl0Pv.png', 9),
('https://imgur.com/G7eSUX0.png', 9),
('https://imgur.com/VQv74hb.png', 10),
('https://imgur.com/BQnCiHr.png', 10),
('https://imgur.com/01tjRhd.png', 10),
('https://imgur.com/M0SncsA.png', 11),
('https://imgur.com/5mTuLn7.png', 11),
('https://imgur.com/EDPjmnE.png', 11),
('https://imgur.com/FOX7s7J.png', 12),
('https://imgur.com/Tm6boRk.png', 12),
('https://imgur.com/o5ml4Sw.png', 12);
