CREATE TABLE locations (
  locationsId INT NOT NULL AUTO_INCREMENT,
  country VARCHAR(50) NOT NULL,
  city VARCHAR(50) NOT NULL,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (locationsId)
);

CREATE TABLE houses (
  houseId INT NOT NULL AUTO_INCREMENT,
  title VARCHAR(100) NOT NULL,
  locationsId INT NOT NULL,
  price DECIMAL(10,2) NOT NULL,
  rating DECIMAL(3,2) NOT NULL,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (houseId),
  UNIQUE KEY unique_location (locationsId),
  CONSTRAINT fk_house_location
    FOREIGN KEY (locationsId)
    REFERENCES locations(locationsId)
    ON DELETE CASCADE
    ON UPDATE CASCADE
);

CREATE TABLE images (
  imagesId INT NOT NULL AUTO_INCREMENT,
  houseId INT NOT NULL,
  src VARCHAR(255) NOT NULL,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (imagesId),
  CONSTRAINT fk_image_house
    FOREIGN KEY (houseId)
    REFERENCES houses(houseId)
    ON DELETE CASCADE
    ON UPDATE CASCADE
);
